sudo: required
services: 
  - docker

before_install:
  - docker build -t tusharkhairnar/docker-react -f Dockerfile.Dev .

script:
  - docker run tusharkhairnar/docker-react npm run test -- --coverage
