sudo: required
services: 
  - docker

before_build:
  - docker build -t tusharkhairnar/docker-react -f Dockerfile.Dev .

scripts:
  - docker run tusharkhairnar/docker-react npm run test -- --coverage
